In [1]:
import numpy as np

In [2]:
a=np.array([[2,3,4,5,4],[6,7,8,9,3]])
print(a)

[[2 3 4 5 4]
 [6 7 8 9 3]]


In [3]:
b=np.array([[2,3,9,8,4],[6,3,8,9,3]])
print(b)

[[2 3 9 8 4]
 [6 3 8 9 3]]


In [4]:
print(a+b)

[[ 4  6 13 13  8]
 [12 10 16 18  6]]


In [5]:
print(a-b)

[[ 0  0 -5 -3  0]
 [ 0  4  0  0  0]]


In [6]:
print(a*b)

[[ 4  9 36 40 16]
 [36 21 64 81  9]]


In [7]:
print(a*5)

[[10 15 20 25 20]
 [30 35 40 45 15]]
