In [1]:
import numpy as np

In [87]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [88]:
b= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [89]:
c = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [10 20 30 40]]]


In [90]:
print(a[2],[2])


3 [2]


In [91]:
print(a[2:4])

[3 4]


In [92]:
print(a[2:])

[3 4 5]


In [93]:
print(b[1,2])

8


In [94]:
print(c[1,2,2])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
print(a.shape)
print(b.shape)

In [95]:
print(a+b)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [96]:
print(a-b)

[[ 0  0  0  0  0]
 [-5 -5 -5 -5 -5]]


In [97]:
print(a*b)

[[ 1  4  9 16 25]
 [ 6 14 24 36 50]]


In [98]:
print(5*b)

[[ 5 10 15 20 25]
 [30 35 40 45 50]]


In [99]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [100]:
print(a)

[1 2 3 4 5]


In [101]:
print(np.median(a))

3.0


In [102]:
print(np.mod(a))

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given